---
title: "Research"  # any name you want here
description: I study coral reef ecology with a particular interest in Mesophotic Coral Ecosystems. My ultimate goal is to use quantitative ecology analysis to increase our knowledge of coral reef functioning and advise on the conservation planning of coral reefs with climate change.

output:
  distill::distill_article:
    toc: true
    css:
      - css/jhelvy.css
      - css/small-spacing.css
twitter:
  creator: "@Perez_Rosales_G"
base_url: https://gonzaloperezrosales.netlify.app/
---

 
## List of publications 

Jia Y, Zhang WG, Lentz SJ, Mollica NR, **Pérez-Rosales G**, Cohen AL. Fine-scale hydrodynamic variability at Majuro Atoll, Republic of the Marshall islands. Part I: Flow variability. Progress in Oceanography. https://doi.org/10.1016/j.pocean.2025.103648 

**Pérez-Rosales G**, Rouzé H, Pichon M, Bongaerts P, Bregere N, Carlot J, UTP Consortium, Parravicini V, Hédouin L. (2024) Differential strategies developed by two light-dependent scleractinian corals to extend their vertical range to mesophotic depths. Coral Reefs https://doi.org/10.1007/s00338-024-02544-2

Radice V, Hernández-Agreda A, **Pérez-Rosales G**, et. al, Bongaerts P. (2024) Recent trends and biases in mesophotic ecosystem research. Biology Letters https://doi.org/10.1098/rsbl.2024.0465 (equal contribution to the study)

Colin JA, Lock C, **Pérez-Rosales G**, Rouzé H, Loreto Paulino Jr. L, Raymundo LJ, Bentlage B. (2024) Symbiodiniaceae phenotypic traits as stress bioindicators for coral transplantation and cold-water bleaching. Marine Pollution Bulletin https://doi.org/10.1016/j.marpolbul.2024.117250

**Pérez-Rosales G**, Hernández-Agreda A, Bongaerts P, Rouzé H, Pichon M, Carlot J, Torda G, UTP Consortium, Hédouin L, Parravicini V. (2022) Mesophotic depths hide high coral cover communities in French Polynesia. Science of the Total Environment https://doi.org/10.1016/j.scitotenv.2022.157049 

**Pérez-Rosales G**, Pichon M, Rouzé H, Villeger S, Torda G, Carlot J, Bongaerts P, UTP Consortium, Parravicini V, Hédouin L. (2022) Mesophotic coral ecosystems of French Polynesia are hotspots of alpha and beta generic diversity for scleractinian assemblages. Diversity & Distribution https://doi.org/10.1111/ddi.13549

**Pérez-Rosales G**, Brandl SJ, Chancerelle Y, Siu G, Martinez E, Parravicini V, Hédouin L. (2021) Documenting decadal disturbance dynamics reveals archipelago-specific recovery and compositional change on Polynesian reefs. Marine Pollution Bulletin; 170:112659. https://doi.org/10.1016/j.marpolbul.2021.112659

**Pérez-Rosales G**, Rouzé H, Torda G, Bongaerts P, Pichon M, Parravicini V, Hédouin L. (2021) Mesophotic coral communities escape thermal coral bleaching in French Polynesia. R. Soc. Open Sci. 8: 210139. https://doi.org/10.1098/rsos.210139

Raick X, Parmentier E, Gervaise C, Lecchini D, Under The Pole Consortium, **Pérez-Rosales G**, Rouzé H, Bertucci F, Di Iorio L. (2024) Invertebrate sounds from photic to mesophotic coral reefs reveal vertical stratification and diel diversity. Oecologia 205, 307-322. https://doi.org/10.1007/s00442-024-05572-5 

Carlot J, Vousdoukas M, Rovere A, Karambas T, Lenihan HS, Kayal M, Adjeroud M, **Pérez-Rosales G**, Hedouin L, Parravicini V. Coral reef structural complexity loss exposes coastlines to waves. Scientific Reports. 13(1):1683 https://doi.org/10.1038/s41598-023-28945-x  

Raick X, Di Iorio L, Lecchini D, Gervaise C, Hédouin L, **Pérez-Rosales G**, Rouzé H, Bertucci F, Parmentier É. (2023) Fish sounds of photic and mesophotic coral reefs: variation with depth and type of island. Coral Reefs https://doi.org/10.1007/s00338-022-02343-7

Carlot J, Rouzé H, Barneche DR, Mercière A, Espiau B, Cardini U, Brandl DJ, Casey JM, **Pérez-Rosales G**, Adjeroud M, Hédouin L, Parravicini V. (2022) Scaling up calcification, respiration, and photosynthesis rates of six prominent coral taxa. Ecology and Evolution https://doi.org/10.1002/ece3.8613 

Rouzé H, Galand PE, Medina M, Bongaerts P, Pichon M, **Pérez-Rosales G**, Torda G, Moya A, Raina JB, Hédouin L. (2021) Symbiotic associations of the deepest recorded photosynthetic scleractinian coral (172 m depth). The ISME journal; 15(5):1564-8. https://doi.org/10.1038/s41396-020-00857-y

Moritz C, Brandl SJ, Rouzé H, Vii J, **Pérez-Rosales G**, Bosserelle P, Chancerelle Y, Galzin R, Liao V, Siu G, Taiarui M, Nugues MM, Hédouin L. (2021) Long-term monitoring of benthic communities reveals spatial determinants of disturbance and recovery dynamics on coral reefs. Mar. Ecol. Prog. S. 672:141-152. https://doi.org/10.3354/meps13807

Hédouin L, Rouzé H, Berthe C, **Pérez-Rosales G**, Martinez E, Chancerelle Y, Galand PE, Lerouvreur F, Nugues MM, Pochon X, Siu G. (2020) Contrasting patterns of mortality in Polynesian coral reefs following the third global coral bleaching event in 2016. Coral Reefs; 39(4):939-52. https://doi.org/10.1007/s00338-020-01914-w

Bongaerts P, **Perez-Rosales G**, Radice VZ, Eyal G, Gori A, Gress E, Hammerman NM, Hernandez-Agreda A, Laverick J, Muir P, Pinheiro H. (2019) Mesophotic.org: a repository for scientific information on mesophotic ecosystems. Oxford Database; https://doi.org/10.1093/database/baz140

## In review

**Pérez-Rosales G**, Pei Y-D, Bennett-Williams J, King T, Rummel M, Chung TH, Wyatt ASJ. Shallow seasonal stratification ameliorates coral bleaching during record-breaking marine heatwaves in a marginal subtropical system. Coral Reefs

Pei Y-D, Wang S, Skinner C, **Pérez-Rosales G**, Intan AG, Nandi S, Wyatt ASJ. Individual trophic plasticity as a functional trait in mixotrophic corals across an estuarine–oceanic gradient. Proc R Soc Lond B Biol Sci

Zhang WG, Jia Y, Lentz SJ, Mollica N, **Pérez-Rosales G**, Cohen AL. Fine-scale Hydrodynamic Variability at Majuro Atoll, Republic of Marshall Islands. Part II: Residence Time and Temperature Variability. Progress in Oceanography


# In preparation

**Pérez-Rosales G**, Cohen A, Jia Y, Mollica N, Galochkina M, Tong E, Thorrold SR, Zhang G. Pacific island coral communities experience fine-scale spatial and temporal heat variability across heatwaves


## International conferences and workshops

International Coral Reef Symposium (Bremen 2022)|
  - First author oral presentation: Diving deep in French Polynesia reveals new insights on the ecological importance of mesophotic coral ecosystems
  - Oral presentation: Scleractinian coral assemblages on the deeper fore-reef slopes: mesophotic, oligophotic, … or rariphotic?

International Coral Reef Symposium (Remotely-Bremen 2021)
  - Oral presentation: Diving deep in paradise shines new light on the twilight zone: preliminary results of the “deephope” mesophotic programme in french polynesia

European Coral Reef Symposium (Oxford, 2017)
  - Workshop: Delving into the Depths: What do we study on Mesophotic Reefs? 

Workshop: Launching the DEEPHOPE Project. Scientific consortium and Under The Pole (Moorea, 2018)

PSL Research University, Summer Coral Reef Formation, Moorea, French Polynesia (May, 2017)

International Symposium of Marine Science (Gran Canaria, 2014)
  - Assistant
  

## List of non-peer reviewed publications: book chapters, thesis, general articles, etc.

PhD Thesis: Pérez-Rosales, G (2022). Diving deep on the reef slopes in French Polynesia: new insights into mesophotic coral ecosystems - Dépôt électronique des thèses - EPHE PSL

Book Chapter: Pérez-Rosales, G (2020). Les mystères de la zone crépusculaire. Book Étonnants récifs - [CNRS Éditions](https://www.cnrseditions.fr/catalogue/ecologie-environnement-sciences-de-la-terre/etonnants-recifs/)

Journal article: Pérez-Rosales, G (2019). Los ecosistemas mesofóticos. Una esperanza para los arrecifes de coral superficales. Revista InMare Nº3, 15-17

Journal article: Pérez-Rosales, G (2017). Un Paraíso al Borde del Colapso. El blanqueamiento del coral pone en riesgo su futuro. Journal Okeanos. Revista de la Sociedad Atlántica de Oceanógrafos Nº5, 18-22

BSc Thesis: Pérez-Rosales, G (2014). Estado de sobrepesca de las Islas Canarias/The state of overfishing in the Canary Islands - BSc Thesis. Acceda ULPGC

Request for copies [here](mailto:gonzalo.prb@gmail.com)


## .....................................................

Go back to [main page](https://gonzaloperezrosales.netlify.app/)





